### ISSUE TITLE
 Could not compile HLSL.

### ISSUE THREAD

**Issue by ski0090** [microsoft/windows-rs#1654]
I wrote the source code as follows.

```rust
            let mut shader_buffer = None;
            let mut error = None;
            let result = D3DCompile(
                simple_shader::VERTEX.as_ptr() as *const c_void,
                simple_shader::VERTEX.len(),
                &None,
                ptr::null(),
                &None,
                PCSTR(b"main".as_ptr()),
                PCSTR(b"vs_5_0".as_ptr()),
                D3DCOMPILE_DEBUG | D3DCOMPILE_SKIP_OPTIMIZATION,
                0,
                &mut shader_buffer,
                &mut error,
            );
            if result.is_err() {
                dbg!(CStr::from_ptr(
                    error.unwrap().GetBufferPointer() as *const std::os::raw::c_char
                ));
                result?;
            };
            Ok(shader_buffer.unwrap())
```

hlsl is:
```hlsl
pub const VERTEX: &'static str = "float4 main(float4 position : POSITION) : SV_POSITION
{
	return position;
}";
```

하지만 결과는 다음과 같이 나옵니다.

```
[src\window\device.rs:102] err = Error {
    code: 0x8876086C,
    message: ,
}
[src\window\device.rs:103] CStr::from_ptr(error.unwrap().GetBufferPointer() as
                   *const std::os::raw::c_char) = "error X3506: unrecognized compiler target \'vs_5_0[:]  = \n\'\n"

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\window\device.rs:107:30
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\panicking.rs:107
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\panicking.rs:48
   3: enum$<core::option::Option<windows::Windows::Win32::Graphics::Direct3D::ID3DBlob>, 1, 18446744073709551615, Some>::unwrap<windows::Windows::Win32::Graphics::Direct3D::ID3DBlob>
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\option.rs:746
   4: gtk_gstreamer_osd::window::device::Device::add_vertex_shader
             at .\src\window\device.rs:107
   5: gtk_gstreamer_osd::window::InnerApp::new
             at .\src\window\mod.rs:20
   6: gtk_gstreamer_osd::GstreamerOsd::from_widget<gtk::auto::drawing_area::DrawingArea>
             at .\src\lib.rs:35
   7: basic::init_ui
             at .\examples\basic.rs:35
   8: basic::main::closure$0
             at .\examples\basic.rs:46
   9: gio::auto::application::impl$3::connect_activate::activate_trampoline<gtk::auto::application::Application,basic::main::closure$0>
             at C:\Users\ski00\.cargo\registry\src\github.com-1ecc6299db9ec823\gio-0.15.10\src\auto\application.rs:604
  10: g_closure_invoke
  11: g_signal_stop_emission_by_name
  12: g_signal_emit_valist
  13: g_signal_emit
  14: g_application_quit
  15: g_application_run
  16: gio::application::impl$0::run_with_args<gtk::auto::application::Application,alloc::string::String>
             at C:\Users\ski00\.cargo\registry\src\github.com-1ecc6299db9ec823\gio-0.15.10\src\application.rs:30
  17: gio::application::impl$0::run<gtk::auto::application::Application>
             at C:\Users\ski00\.cargo\registry\src\github.com-1ecc6299db9ec823\gio-0.15.10\src\application.rs:23
  18: basic::main
             at .\examples\basic.rs:49
  19: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\basic.exe` (exit code: 101)
```

**Comment by kennykerr** [comment]
Looks like you're getting an error from the API itself, rather than the `windows` crate. For general questions about Windows API, please go here:

https://docs.microsoft.com/en-us/answers/topics/windows-api.html

They should be able to track down the API owner to help you with your question.

**Comment by ski0090** [comment]
Ah, I found a solution. PCSTR requires \0 explicitly
