### ISSUE TITLE
Why CreateDIBSection returns an `Err` when the message tells the operation completed successfully ?

### ISSUE THREAD

**Issue by antoninhrlt** [microsoft/windows-rs#2272]
Today, I've written this in my program:
```rust
self.bitmap = CreateDIBSection(
    self.hdc, 
    &mut self.pixmap.bitmapinfo(), 
    DIB_RGB_COLORS, 
    &mut (self.pixels.as_mut_ptr() as *mut _), 
    HANDLE(0), 
    0
)
```
I realised this function actually returns a `Result<HBITMAP>` value. So, I added `.unwrap();` at the end
But when I ran the program, I got this panic message:
```
thread 'tests::painting' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x00000000), message: "The operation completed successfully." }
```

I'm wondering why is it returning an `Err` instead of an `Ok` even if the operation completed successfully.
Now my problem is that I can't get the returned value of the function

**Comment by antoninhrlt** [comment]
As I see on this issue : #2097, it might be because there is a bad parameter, but how to know what's the problem ?

**Comment by riverar** [comment]
@antoninhrlt Hey there, can you provide a small program that reproduces the issue?

**Comment by antoninhrlt** [comment]
Sure, here is it :
```rust
use windows::{
    core::*, 
    Win32::Foundation::*, 
    Win32::Graphics::Gdi::*,
    Win32::System::LibraryLoader::*, 
    Win32::UI::WindowsAndMessaging::*,
};

unsafe extern "system" fn wndproc(hwnd: HWND, message: u32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    DefWindowProcA(hwnd, message, wparam, lparam)
}

fn main() {
    unsafe {
        let instance = GetModuleHandleA(None)
            .expect("unable to initialise win32 instance");

        let wc = WNDCLASSA {
            style: CS_HREDRAW | CS_VREDRAW | CS_OWNDC,
            lpfnWndProc: Some(wndproc),
            hInstance: instance,
            lpszClassName: PCSTR("Test".as_ptr()),
            hbrBackground: CreateSolidBrush(COLORREF(0x00000000)),
            ..Default::default()
        };
        
        if RegisterClassA(&wc) == 0 {
            panic!("unable to register the window class");
        }
        
        let hwnd = CreateWindowExA(
            WINDOW_EX_STYLE::default(),
            PCSTR("Test".as_ptr()),
            PCSTR("Test".as_ptr()),
            WS_OVERLAPPEDWINDOW | WS_VISIBLE,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            720,
            480,
            None,
            None,
            instance,
            None,
        );

        if hwnd == HWND(0) {
            panic!("unable to create the window");
        }

        let hdc = GetDC(hwnd);

        let mut pixels: Vec<u32> = vec![0; 720 * 480];

        let bitmap = CreateDIBSection(
            hdc, 
            &mut BITMAPINFO {
                bmiHeader: BITMAPINFOHEADER {
                    biWidth: 720,
                    // Negative height makes top left as the coordinate system 
                    // origin.
                    biHeight: -480,
                    biPlanes: 1,
                    biCompression: BI_RGB,
                    ..Default::default()
                },
                ..Default::default()
            }, 
            DIB_RGB_COLORS, 
            &mut (pixels.as_mut_ptr() as *mut _), 
            None, 
            0
        )
        .unwrap();
    }
}
```
"Cargo.toml":
```toml
[package]
name = "issue"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os="windows")'.dependencies.windows]
version = "0.43.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]
```

This is the error message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x00000000), message: "The operation completed successfully." }', src\main.rs:73:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\result.rs:1814
   3: enum$<core::result::Result<windows::Windows::Win32::Graphics::Gdi::HBITMAP,windows::core::error::Error> >::unwrap<windows::Windows::Win32::Graphics::Gdi::HBITMAP,windows::core::error::Error>
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\result.rs:1107
   4: issue::main
             at .\src\main.rs:54
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kennykerr** [comment]
The problem is that, as with #2097, the `CreateDIBSection` function does not reliably or set the last error upon failure. You can see this by calling `SetLastrError` with a token error code before calling `CreateDIBSection` and you should see your token value reported by the failure following the call to `CreateDIBSection`. 

Anyway, calling the `CreateDIBSection` function can be challenging. You have to be very careful to prepare the parameters correctly. At a glance, you're failing to set the header's `biSize` field to the size of the header struct. I suggest reading the documentation very carefully. I also wrote about this struct here:

https://learn.microsoft.com/en-us/archive/msdn-magazine/2009/december/windows-with-c-layered-windows-with-direct2d

Hope that helps.

**Comment by antoninhrlt** [comment]
I'm now doing creating the bitmap info as following:
```rust
let mut bitmapinfo = BITMAPINFO::default();

bitmapinfo.bmiHeader.biSize = std::mem::size_of_val(&bitmapinfo.bmiHeader) as u32;
bitmapinfo.bmiHeader.biWidth = self.width as i32;
// Negative height makes top left as the coordinate system origin.
bitmapinfo.bmiHeader.biHeight = -(self.height as i32);
bitmapinfo.bmiHeader.biPlanes = 1;
bitmapinfo.bmiHeader.biBitCount = 32;
bitmapinfo.bmiHeader.biCompression = BI_RGB;

bitmapinfo
```
And it works ! Thank you, I'm also reading your article.
I guess I can close this issue.
